language: java
sudo: false
arch:
    - amd64
    - ppc64le
jdk:
  - openjdk8
  - openjdk11
  - openjdk15
  - openjdk-ea
before_install:
        - mkdir -p /opt/maven
        - curl https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz%7Ctar -xz --strip 1 -C /opt/maven
        - export MAVEN_HOME=/opt/maven
        - export PATH=${MAVEN_HOME}/bin:${PATH}
matrix:
  allow_failures:
    - jdk: openjdk-ea
after_success:
  - mvn -V clean cobertura:cobertura coveralls:report --no-transfer-progress
